# -*- coding: utf-8 -*-
"""
/***************************************************************************
 treebeard
                                 A QGIS plugin
 Delineates tree groupings in raster mosaic datasets and reports spatial heterogeneity statistics for forest land
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-20
        copyright            : (C) 2024 by Chris Griego, Ed Chan, Peter Kobylarz
        email                : chgr/2106@colorado.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load treebeard class from file treebeard.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .treebeard import Treebeard
    return Treebeard(iface)
