# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Degg\Documents\GitHub\treebeard\qgis_build\treebeard\import_lidar_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_import_lidar_dialog(object):
    def setupUi(self, import_lidar_dialog):
        import_lidar_dialog.setObjectName("import_lidar_dialog")
        import_lidar_dialog.resize(376, 99)
        self.importLidarComboBox = QtWidgets.QComboBox(import_lidar_dialog)
        self.importLidarComboBox.setGeometry(QtCore.QRect(20, 20, 191, 22))
        self.importLidarComboBox.setObjectName("importLidarComboBox")
        self.importLidarComboBox.addItem("")
        self.importLidarComboBox.addItem("")
        self.importLidarComboBox.addItem("")
        self.confrimOK = QtWidgets.QPushButton(import_lidar_dialog)
        self.confrimOK.setGeometry(QtCore.QRect(250, 20, 93, 28))
        self.confrimOK.setObjectName("confrimOK")
        self.confirmCancel = QtWidgets.QPushButton(import_lidar_dialog)
        self.confirmCancel.setGeometry(QtCore.QRect(250, 60, 93, 28))
        self.confirmCancel.setObjectName("confirmCancel")

        self.retranslateUi(import_lidar_dialog)
        QtCore.QMetaObject.connectSlotsByName(import_lidar_dialog)

    def retranslateUi(self, import_lidar_dialog):
        _translate = QtCore.QCoreApplication.translate
        import_lidar_dialog.setWindowTitle(_translate("import_lidar_dialog", "Dialog"))
        self.importLidarComboBox.setItemText(0, _translate("import_lidar_dialog", "Import from QGIS Layer"))
        self.importLidarComboBox.setItemText(1, _translate("import_lidar_dialog", "Import from Dataset"))
        self.importLidarComboBox.setItemText(2, _translate("import_lidar_dialog", "Import from Desktop"))
        self.confrimOK.setText(_translate("import_lidar_dialog", "OK"))
        self.confirmCancel.setText(_translate("import_lidar_dialog", "Cancel"))
