# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Degg\Documents\GitHub\treebeard\qgis_build\treebeard\settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(274, 124)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(180, 30, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buffer_chkbox = QtWidgets.QCheckBox(Dialog)
        self.buffer_chkbox.setGeometry(QtCore.QRect(30, 30, 191, 21))
        self.buffer_chkbox.setObjectName("buffer_chkbox")
        self.png_chkbox = QtWidgets.QCheckBox(Dialog)
        self.png_chkbox.setGeometry(QtCore.QRect(30, 50, 151, 20))
        self.png_chkbox.setObjectName("png_chkbox")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buffer_chkbox.setText(_translate("Dialog", "Enable Buffering"))
        self.png_chkbox.setText(_translate("Dialog", "Generates PNGs"))
