# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treebeard_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_treebeardDialogBase(object):
    def setupUi(self, treebeardDialogBase):
        treebeardDialogBase.setObjectName("treebeardDialogBase")
        treebeardDialogBase.resize(486, 204)
        self.label = QtWidgets.QLabel(treebeardDialogBase)
        self.label.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(treebeardDialogBase)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 131, 41))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(treebeardDialogBase)
        self.lineEdit.setGeometry(QtCore.QRect(170, 20, 171, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(treebeardDialogBase)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 50, 171, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(treebeardDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(370, 20, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(treebeardDialogBase)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 50, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(treebeardDialogBase)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 130, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(treebeardDialogBase)
        QtCore.QMetaObject.connectSlotsByName(treebeardDialogBase)

    def retranslateUi(self, treebeardDialogBase):
        _translate = QtCore.QCoreApplication.translate
        treebeardDialogBase.setWindowTitle(_translate("treebeardDialogBase", "Treebeard"))
        self.label.setText(_translate("treebeardDialogBase", "Select Boundary Polygon"))
        self.label_2.setText(_translate("treebeardDialogBase", "Select Raster Set"))
        self.pushButton.setText(_translate("treebeardDialogBase", "Browse"))
        self.pushButton_2.setText(_translate("treebeardDialogBase", "Browse"))
        self.pushButton_3.setText(_translate("treebeardDialogBase", "Process"))
